### ISSUE TITLE
DisallowedHost at /housing on 2017.civicpdx.org

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#107]
Having migrated the 2017 project web sites to the Lerna monorepo, deploying as an Express-hosting Docker container, we now need to update the ALLOWED_HOSTS configuration for each of those web sites:

```
DisallowedHost at /housing
Invalid HTTP_HOST header: '2017.civicpdx.org'. You may need to add '2017.civicpdx.org' to ALLOWED_HOSTS.

Request Method: | GET
-- | --
http://2017.civicpdx.org/housing
1.10.5
DisallowedHost
Invalid HTTP_HOST header: '2017.civicpdx.org'. You may need to add '2017.civicpdx.org' to ALLOWED_HOSTS.
/usr/local/lib/python3.5/site-packages/django/http/request.py in get_host, line 113
/usr/local/bin/python3.5
```

Get each site updated:
- [ ] /budget
- [ ] /emergency
- [ ] /homeless
- [ ] /housing
- [ ] /transport

**Comment by MikeTheCanuck** [comment]
It's also possible this is an artifact of a bad build of the `2017` civic package (https://github.com/hackoregon/civic/tree/master/packages/2017), and that there should not have been Django errors in the first place coming from there.

**Comment by iant01** [comment]
This issue can probably be closed. It is a red herring in that due to the ordering of the load balancer listner rules with the new services (civic-2017 and civic-2018) the requests were being handed off to the old 2017 service which do not expect to get something from 2017.civicpdx.org or staging2018.civicpdx.org host domains.

**Comment by iant01** [comment]
closing as resolved by listener rule changes.
