### ISSUE TITLE
Remove the "400" HttpCode from the health check in all Fargate services

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#245]
Remove the "400" HttpCode from the TargetGroup > Properties > Matcher configuration in all Fargate services - which will require:
1. figuring out why the containerized app (or its Task, or its Service, or the ALB Health Check) is seeing a 400 response from containers that do not return such a response when deployed in ECS as EC2 services
2. Addressing the problem
3. Redeploying and testing that ECS still considers such tasks "healthy"

The HttpCode should just allow "200-299" as healthy responses, but in my efforts to convert EC2 services into Fargate, I ran into an inexplicable problem where the health check wouldn't pass, with no specific logs telling us why, and no indication that the Django app was actually returning this error, so I added the 400 response to the health check configuration so that the Fargate tasks would get scheduled into active duty:
https://github.com/hackoregon/civic-devops/issues/244#issuecomment-506995680

**Comment by MikeTheCanuck** [comment]
Confirmed: the health check on the 2017 API containerized Fargate Tasks is definitely receiving a 400 response e.g.:
`10.180.13.204 [30/Jun/2019:19:22:06 +0000] GET /emergency/ HTTP/1.1 400 26 - ELB-HealthChecker/2.0 0.011522`

**Comment by DingoEatingFuzz** [comment]
After digging into this error I first learned that the 400 was coming from django and may not be AWS environment related. I then learned that the 2017 Emergency Response project was very misconfigured. I finally learned that after addressing the issues with the 2017 Emergency Response project that the health check returns the expected 200.

It's hard to say what the actual issue was. We may have to accept that it is lost to time.

**Comment by MikeTheCanuck** [comment]
Bad news: currently all the endpoints on the 2017 /emergency API are returning 500 error:

<img width="630" alt="Screen Shot 2019-06-30 at 18 27 50" src="https://user-images.githubusercontent.com/6953053/60405378-9b891d00-9b64-11e9-85e9-f3342d431cdb.png">

I can confirm that I tested out a handful of those endpoints earlier today and they were returning valid responses (JSON data).

I tried out https://github.com/hackoregon/hackoregon-aws-infrastructure/pull/73 but given this challenge, I'd prefer to test on a clean working Task and not further complicate any current troubleshooting.

**Comment by DingoEatingFuzz** [comment]
The root cause of the 500 is a bad db connection, which I am 99% sure is because the container isn't getting the db credentials env vars.

@MikeTheCanuck, do you recall how env vars were passed from Travis along to the container in 2017? At some point all the scripts in this repo were updated to the 2018 method that relies on the parameter store, but it has never actually worked.

I've been bludgeoning the env vars into place in, but I suspect there is a more elegant way this was being done.

**Comment by DingoEatingFuzz** [comment]
Never mind, as soon as I said that I remembered that they were being copied down from s3.

Found the relevant diff in 2017 emergency services: https://github.com/hackoregon/emergency-response-backend/commit/168fb54ef8553567a6ddb0935eba11207acd3111#diff-35f523ecb43eb88f8358e525fe9c8a80

So the issue here, which probably happened elsewhere, is that the deploy scripts were updated to use the `get-ssm-parameters` script but the configuration was never actually added to the parameter store.

**Comment by MikeTheCanuck** [comment]
Consider this resolved as of PR https://github.com/hackoregon/hackoregon-aws-infrastructure/pull/71
