### ISSUE TITLE
Automate the shutdown of AWS resources overnight

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#67]
Ian has been great about offering us the option of saving some billing $$ by turning off most resources overnight (e.g. midnight-6am - which would shave up to 1/4 off the monthly AWS bill).

We could certainly use this when we have a spare moment.  Automation and/or AWS console configuration (and documentation to explain how it's enabled and can be disabled) of this would be necessary before implementing.

However there's at least one risk that prevents us from moving forward on this - at least for our PostgreSQL boxes in EC2, all of them only preserve their IP address because they've never been shut down.  What would it take - and how much would it cost - to ensure the IP addresses stay stable, and/or setup DNS A/CNAME records for each service that tracked the every-night-changing IP addresses?

**Comment by iant01** [comment]
The database instances are not in route53 (DNS,A/CNAME) so that is not a factor. in order to stop/start the database instances, they would need to be assigned and attached EIPs and any API code and or environment variable setting for the DBHOST IP address, changed to match the correct EIP for the corect DB instance. Currently there are no cloudformation templates or stack(s) for the database instances. When/If those are created, they would need to be setup to reuse the EIPs for the correct Instances. Would make things easier if they were moved all to one DB instance like the 2018 DB.

As for the large ECS instances, they can be automated through the auto scaling group which will keep the load balancer in sync with the new target IP/Port for the containers/service APIs. as they change.
