### ISSUE TITLE
Cannot `ssh` into Bastion Host in newly created stack

### ISSUE THREAD

**Issue by khashf** [hackoregon/civic-devops#90]
This issue was previously mentioned at issue #87 

@MikeTheCanuck suspects that the security group assigned to the Bastion Host only allows certain IP addresses incoming. The below screenshot showed that this host allows `tcp/22` from anywhere but both Mike and me got `Connect time out` 

![image](https://user-images.githubusercontent.com/6059347/39965428-52cb5f90-564d-11e8-96d3-ca838bc50e4f.png)

**Comment by MikeTheCanuck** [comment]
@khashf for the sake of my failing memory, and for everyone else's sake, could you please outline the reason why you need to SSH into the Bastion Host in the first place?

Was it because we thought that might be one way to then SSH into the EC2 hosts that are running the ECS containers, so that we might examine any of the logs that are only visible from the host OS (not the container "guests" i.e. the ECS Task Logs tab)?

And what was the root problem we wanted to solve, for which those EC2 host logs might be helpful?  I feel like we might have gone down a rabbit hole, and might need to re-focus on what the original problem is, to find some other way to attack it.

**Comment by MikeTheCanuck** [comment]
BTW, here's where we defined the **BastionHostSecurityGroup** that generates the rules in the HackO AWS:
https://s3-us-west-2.amazonaws.com/hacko-infrastructure-cfn/infrastructure/security-groups.yaml

All I can say is to triple-check this.  Otherwise I'm stumped.

**Comment by khashf** [comment]
I got into BastionHost!

The security group attached to the BastionHost define a weird protocol - `XNS-IDP` - very ancient protocol and I don't know why on earth it was decided to be attached on BastionHost on the first place. I changed it to `TCP` and it works as expected.


> Was it because we thought that might be one way to then SSH into the EC2 hosts that are running the ECS containers, so that we might examine any of the logs that are only visible from the host OS (not the container "guests" i.e. the ECS Task Logs tab)?

=> Yes, this is the reason I wanted to get in.
